/**
 * @file hamiltonian_equations.h
 * @brief Hamilton's canonical equations and numerical solvers.
 *
 * Reference: Goldstein Ch.8, Landau-Lifshitz Vol.1 Ch.7
 *            Hairer, Lubich, Wanner — Geometric Numerical Integration (2006)
 *
 * L4 Fundamental Laws: Hamilton's equations dq/dt = dH/dp, dp/dt = -dH/dq
 * L5 Computational Methods: Symplectic integrators and ODE solver framework
 */

#ifndef HAMILTONIAN_EQUATIONS_H
#define HAMILTONIAN_EQUATIONS_H

#include "hamiltonian_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ================================================================
 * L4: Hamilton's equations of motion
 * ================================================================ */

/** Evaluate Hamilton's RHS: dq/dt = dH/dp, dp/dt = -dH/dq.
 *  Theorem (Energy Conservation): dH/dt = {H, H} = 0 for autonomous H.
 *  Theorem (Liouville): the flow preserves phase space volume.
 *  O(n) per evaluation (dominated by grad_H callback). */
void hamiltons_rhs(const HamiltonianSystem *sys,
                   const double *q, const double *p,
                   double *dq, double *dp);

/** Hamiltonian vector field X_H = J · grad_H = (dH/dp, -dH/dq).
 *  The flow phi_t generated by X_H preserves the symplectic form. */
void hamiltonian_vector_field(size_t n,
                               const double *dH_dq, const double *dH_dp,
                               double *X);

/** Time derivative of an observable: df/dt = {f, H} + df/dt_explicit.
 *  Classical analogue of Heisenberg equation: dA/dt = (i/hbar)[H, A]. */
double time_derivative_observable(const HamiltonianSystem *sys,
                                   Observable f,
                                   const double *q, const double *p,
                                   double eps);

/* ================================================================
 * L5: Symplectic integrators
 * ================================================================ */

/** Stormer-Verlet (2nd order symplectic, leapfrog/velocity Verlet).
 *
 *  For separable H = T(p) + V(q):
 *    p_{n+1/2} = p_n - (h/2)·grad_V(q_n)
 *    q_{n+1}   = q_n +  h ·grad_T(p_{n+1/2})
 *    p_{n+1}   = p_{n+1/2} - (h/2)·grad_V(q_{n+1})
 *
 *  Properties: symplectic, time-reversible, 2nd order.
 *  Long-term energy error bounded (backward error analysis).
 *
 *  Reference: Hairer et al. (2006), Geometric Numerical Integration, Ch.1 */
void stormer_verlet_step(const HamiltonianSystem *sys,
                          const double *q, const double *p,
                          double dt,
                          double *q_new, double *p_new);

/** Symplectic Euler (1st order, q-first variant).
 *
 *    q_{n+1} = q_n + h·dH/dp(q_n, p_n)
 *    p_{n+1} = p_n - h·dH/dq(q_{n+1}, p_n)
 *
 *  Symplectic but not time-reversible. When composed with its adjoint
 *  yields Stormer-Verlet (Trotter-Suzuki decomposition). */
void symplectic_euler_step(const HamiltonianSystem *sys,
                            const double *q, const double *p,
                            double dt,
                            double *q_new, double *p_new);

/** Ruth 4th-order symplectic integrator (Forest-Ruth, 1990).
 *
 *  Minimum-stage 4th-order symmetric composition using 3 force evaluations.
 *  Coefficients: c1=c4 = 1/(2(2-2^{1/3})), c2=c3 = (1-2^{1/3})/(2(2-2^{1/3}))
 *               d1=d3 = 1/(2-2^{1/3}), d2 = -2^{1/3}/(2-2^{1/3}), d4=0
 *
 *  Reference: Forest & Ruth, Physica D 43, 105-117 (1990) */
void ruth4_step(const HamiltonianSystem *sys,
                 const double *q, const double *p,
                 double dt,
                 double *q_new, double *p_new);

/** Yoshida 6th-order symplectic integrator.
 *
 *  Constructed by composing three 2nd-order leapfrog steps with
 *  irrationally-related step sizes (Yoshida 1990).
 *
 *  w0 = -0.117767998417887e-1, w1 = 0.235573213359357,
 *  w2 = 0.784513610477560, w3 = 1 - 2(w0+w1+w2) with symmetric repetition.
 *
 *  Reference: Yoshida, Phys. Lett. A 150, 262-268 (1990) */
void yoshida6_step(const HamiltonianSystem *sys,
                    const double *q, const double *p,
                    double dt,
                    double *q_new, double *p_new);

/** Solve Hamilton's equations with fixed-step integration.
 *
 *  @param sys         Hamiltonian system
 *  @param q0, p0      Initial conditions [n]
 *  @param t_end       End time
 *  @param dt          Fixed step size
 *  @param integrator  Symplectic method choice
 *  @param traj        Pre-allocated trajectory
 *  @param record_every Record interval
 *  @return            Number of steps taken */
size_t solve_hamiltonian(const HamiltonianSystem *sys,
                          const double *q0, const double *p0,
                          double t_end, double dt,
                          IntegratorType integrator,
                          PhaseTrajectory *traj,
                          size_t record_every);

/** RK4 step (non-symplectic, for comparison).
 *  Higher formal accuracy but systematic energy drift over long times. */
void rk4_hamiltonian_step(const HamiltonianSystem *sys,
                           const double *q, const double *p,
                           double dt,
                           double *q_new, double *p_new);

/** Create integrator descriptor with full metadata. */
IntegratorDescriptor integrator_descriptor_create(IntegratorType type);

/** Free integrator descriptor. */
void integrator_descriptor_free(IntegratorDescriptor *desc);

/* ================================================================
 * Energy diagnostics
 * ================================================================ */

/** Relative energy drift: max_i |H(t_i) - H(t_0)| / |H(t_0)|.
 *  For symplectic integrators, drift remains bounded for exponentially
 *  long times (backward error analysis of Hairer & Lubich). */
double energy_drift(const PhaseTrajectory *traj);

/** Action drift for integrable systems. For exact flow: J = const. */
double action_drift(const PhaseTrajectory *traj,
                     const ActionAngleSystem *aas);

/** Quick energy check: |H(q,p) - E_expected| / |E_expected|. */
double energy_error(const HamiltonianSystem *sys,
                     const double *q, const double *p,
                     double E_expected);

#ifdef __cplusplus
}
#endif

#endif /* HAMILTONIAN_EQUATIONS_H */
