/**
 * @file hamiltonian_lie.c
 * @brief Lie-Poisson bracket, structure constants, and rigid body dynamics.
 *
 * Implements: Lie-Poisson bracket on g*, SO(3) structure constants,
 * Euler rigid body equations, symplectic form, momentum maps,
 * Marsden-Weinstein reduction.
 *
 * Reference: Marsden & Ratiu, Introduction to Mechanics and Symmetry (1999)
 *            Arnold, Mathematical Methods of Classical Mechanics, Appendix 2
 *
 * Knowledge coverage:
 *   L3: Lie algebra, structure constants, Lie-Poisson bracket
 *   L8: Marsden-Weinstein symplectic reduction, momentum maps
 *
 * University mapping:
 *   Berkeley PHYS 242 — Lie-Poisson structure, Marsden-Weinstein reduction
 *   Cambridge Part II — Symplectic geometry and Lie group actions
 *   Oxford CMT — Geometric mechanics and momentum maps
 */

#include "hamiltonian_types.h"
#include "hamiltonian_poisson.h"
#include "hamiltonian_symplectic.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* ──────────────────────────────────────────────────────────────
 * Symplectic form evaluation
 *
 * ω(ξ, η) = Σ_i (δq_i · δp'_i - δp_i · δq'_i)
 *         = ξ^T · J · η
 *
 * This is the canonical symplectic form in Darboux coordinates.
 * For any Hamiltonian flow φ_t, we have φ_t^* ω = ω.
 * ────────────────────────────────────────────────────────────── */

double symplectic_form_eval(size_t n,
                             const double *dq1, const double *dp1,
                             const double *dq2, const double *dp2) {
    if (!dq1 || !dp1 || !dq2 || !dp2) return 0.0;
    double omega = 0.0;
    for (size_t i = 0; i < n; i++) {
        omega += dq1[i] * dp2[i] - dp1[i] * dq2[i];
    }
    return omega;
}

void symplectic_form_matrix(size_t n, double *J_out) {
    if (!J_out) return;
    size_t n2 = 2 * n;
    memset(J_out, 0, n2 * n2 * sizeof(double));
    for (size_t i = 0; i < n; i++) {
        J_out[i * n2 + (n + i)] =  1.0;  /* Upper-right block: I_n */
        J_out[(n + i) * n2 + i] = -1.0;  /* Lower-left block: -I_n */
    }
}

/* ──────────────────────────────────────────────────────────────
 * Symplectic gradient: X_f = J · ∇f
 *
 * In Darboux coordinates:
 *   X_f = (∂f/∂p, -∂f/∂q)
 *
 * This is the Hamiltonian vector field generated by the observable f.
 * Its flow preserves f: L_{X_f} f = {f, f} = 0.
 * ────────────────────────────────────────────────────────────── */

void symplectic_gradient(Observable f,
                          const double *q, const double *p, size_t n,
                          double eps,
                          double *X_f) {
    if (!f || !q || !p || !X_f || eps <= 0.0) return;

    double *qp = (double *)malloc(n * sizeof(double));
    double *qm = (double *)malloc(n * sizeof(double));
    double *pp = (double *)malloc(n * sizeof(double));
    double *pm = (double *)malloc(n * sizeof(double));
    if (!qp || !qm || !pp || !pm) {
        free(qp); free(qm); free(pp); free(pm); return;
    }

    for (size_t i = 0; i < n; i++) {
        memcpy(qp, q, n*sizeof(double)); qp[i] += eps;
        memcpy(qm, q, n*sizeof(double)); qm[i] -= eps;
        double df_dq = (f(qp, p, n) - f(qm, p, n)) / (2.0 * eps);

        memcpy(pp, p, n*sizeof(double)); pp[i] += eps;
        memcpy(pm, p, n*sizeof(double)); pm[i] -= eps;
        double df_dp = (f(q, pp, n) - f(q, pm, n)) / (2.0 * eps);

        X_f[i]     =  df_dp;   /* ∂f/∂p_i */
        X_f[n + i] = -df_dq;   /* -∂f/∂q_i */
    }

    free(qp); free(qm); free(pp); free(pm);
}

/* ──────────────────────────────────────────────────────────────
 * Symplectic matrix utilities
 * ────────────────────────────────────────────────────────────── */

bool is_symplectic_matrix_direct(const double *M, size_t n, double tol) {
    if (!M) return false;
    size_t n2 = 2 * n;
    double *J = (double *)malloc(n2 * n2 * sizeof(double));
    double *MJ = (double *)malloc(n2 * n2 * sizeof(double));
    double *MTJM = (double *)malloc(n2 * n2 * sizeof(double));
    if (!J || !MJ || !MTJM) {
        free(J); free(MJ); free(MTJM); return false;
    }

    symplectic_form_matrix(n, J);

    /* MJ = M · J */
    for (size_t i = 0; i < n2; i++) {
        for (size_t j = 0; j < n2; j++) {
            double s = 0.0;
            for (size_t k = 0; k < n2; k++) {
                s += M[i * n2 + k] * J[k * n2 + j];
            }
            MJ[i * n2 + j] = s;
        }
    }

    /* MTJM = M^T · (M · J) */
    for (size_t i = 0; i < n2; i++) {
        for (size_t j = 0; j < n2; j++) {
            double s = 0.0;
            for (size_t k = 0; k < n2; k++) {
                s += M[k * n2 + i] * MJ[k * n2 + j];  /* M^T[i,k] = M[k,i] */
            }
            MTJM[i * n2 + j] = s;
        }
    }

    /* Check MTJM == J within tol */
    double max_err = 0.0;
    for (size_t i = 0; i < n2; i++) {
        for (size_t j = 0; j < n2; j++) {
            double err = fabs(MTJM[i * n2 + j] - J[i * n2 + j]);
            if (err > max_err) max_err = err;
        }
    }

    free(J); free(MJ); free(MTJM);
    return max_err < tol;
}

SymplecticMatrix symplectic_matrix_alloc(size_t n) {
    SymplecticMatrix J;
    J.n = n;
    size_t n2 = 2 * n;
    J.data = (double *)calloc(n2 * n2, sizeof(double));
    if (J.data) {
        for (size_t i = 0; i < n; i++) {
            J.data[i * n2 + (n + i)] =  1.0;
            J.data[(n + i) * n2 + i] = -1.0;
        }
    }
    return J;
}

void symplectic_matrix_free(SymplecticMatrix *J) {
    if (J) { free(J->data); J->data = NULL; }
}

/* ──────────────────────────────────────────────────────────────
 * Lie-Poisson bracket on the dual g* of a Lie algebra
 *
 * For F, G: g* → R:
 *   {F, G}(μ) = -⟨ μ, [∇F(μ), ∇G(μ)] ⟩
 *            = -Σ_{i,j,k} μ_i · c_{ij}^k · (∂F/∂μ_j)(∂G/∂μ_k)
 *
 * This bracket is the Poisson reduction of the canonical bracket
 * on T*G by the left (or right) action of G on itself.
 *
 * The equations of motion for H: g* → R are:
 *   dμ/dt = ad*_{∇H(μ)} μ
 *
 * Physical realizations:
 *   — Euler rigid body (so(3)*)
 *   — Ideal incompressible fluid (SDiff(M)*)
 *   — Vlasov-Maxwell plasma
 *   — KdV equation (Virasoro algebra coadjoint orbit)
 * ────────────────────────────────────────────────────────────── */

double lie_poisson_bracket(double (*F)(const double *mu, size_t dim),
                            double (*G)(const double *mu, size_t dim),
                            const double *mu, size_t dim,
                            const double *structure_constants,
                            double eps) {
    if (!F || !G || !mu || !structure_constants || eps <= 0.0) return 0.0;

    double *grad_F = (double *)malloc(dim * sizeof(double));
    double *grad_G = (double *)malloc(dim * sizeof(double));
    double *mup = (double *)malloc(dim * sizeof(double));
    double *mum = (double *)malloc(dim * sizeof(double));
    if (!grad_F || !grad_G || !mup || !mum) {
        free(grad_F); free(grad_G); free(mup); free(mum); return 0.0;
    }

    /* Numerical gradients via symmetric finite differences */
    for (size_t i = 0; i < dim; i++) {
        memcpy(mup, mu, dim * sizeof(double)); mup[i] += eps;
        memcpy(mum, mu, dim * sizeof(double)); mum[i] -= eps;
        grad_F[i] = (F(mup, dim) - F(mum, dim)) / (2.0 * eps);
        grad_G[i] = (G(mup, dim) - G(mum, dim)) / (2.0 * eps);
    }

    /* {F, G}(μ) = - Σ_{i,j,k} μ_i · c_{ij}^k · ∂_jF · ∂_kG */
    double result = 0.0;
    for (size_t i = 0; i < dim; i++) {
        for (size_t j = 0; j < dim; j++) {
            for (size_t k = 0; k < dim; k++) {
                double c = structure_constants[i*dim*dim + j*dim + k];
                result -= mu[i] * c * grad_F[j] * grad_G[k];
            }
        }
    }

    free(grad_F); free(grad_G); free(mup); free(mum);
    return result;
}

/* ──────────────────────────────────────────────────────────────
 * SO(3) structure constants: c_{ij}^k = ε_{ijk}
 *
 * The Lie algebra so(3) consists of 3×3 skew-symmetric matrices.
 * Basis: e_1, e_2, e_3 with [e_i, e_j] = ε_{ijk} e_k.
 *
 * Nonzero constants:
 *   c_{12}^3 = c_{23}^1 = c_{31}^2 = +1
 *   c_{21}^3 = c_{32}^1 = c_{13}^2 = -1
 *
 * The dual so(3)* is identified with R^3 via the pairing
 * ⟨μ, ξ⟩ = μ·ξ (Euclidean dot product).
 * Under this identification, the coadjoint action is:
 *   ad*_ξ μ = μ × ξ  (cross product)
 * ────────────────────────────────────────────────────────────── */

void so3_structure_constants(double *c_out) {
    if (!c_out) return;
    memset(c_out, 0, 27 * sizeof(double));
    /* ε_{123} = ε_{231} = ε_{312} = +1 */
    c_out[0*9 + 1*3 + 2] =  1.0;  /* c_{12}^3 */
    c_out[1*9 + 2*3 + 0] =  1.0;  /* c_{23}^1 */
    c_out[2*9 + 0*3 + 1] =  1.0;  /* c_{31}^2 */
    /* ε_{213} = ε_{321} = ε_{132} = -1 */
    c_out[1*9 + 0*3 + 2] = -1.0;  /* c_{21}^3 */
    c_out[2*9 + 1*3 + 0] = -1.0;  /* c_{32}^1 */
    c_out[0*9 + 2*3 + 1] = -1.0;  /* c_{13}^2 */
}

/* ──────────────────────────────────────────────────────────────
 * Euler equations for a free rigid body
 *
 * Lie-Poisson form on so(3)*:
 *   dμ/dt = {μ, H} = μ × ∇H
 *
 * For H(μ) = ½ Σ μ_i² / I_i (rotational kinetic energy):
 *   ∇H = (μ₁/I₁, μ₂/I₂, μ₃/I₃)
 *
 * Hence:
 *   dμ₁/dt = μ₂·(μ₃/I₃) - μ₃·(μ₂/I₂) = μ₂μ₃(1/I₃ - 1/I₂)
 *   dμ₂/dt = μ₃μ₁(1/I₁ - 1/I₃)
 *   dμ₃/dt = μ₁μ₂(1/I₂ - 1/I₁)
 *
 * Conservation laws:
 *   C₁(μ) = |μ|²  (Casimir — conserved for any H)
 *   C₂(μ) = H(μ)  (energy — conserved for this H)
 *
 * The flow lies on the intersection of a sphere (|μ| = const)
 * and an ellipsoid (H = const). This intersection consists of
 * closed orbits (for generic I_i) or separatrices (when two I_i
 * are equal → axial symmetry).
 *
 * The Euler equations exhibit the tennis racket theorem
 * (Dzhanibekov effect): rotation about the intermediate axis
 * of inertia is unstable, while rotation about the largest
 * or smallest principal axis is stable.
 * ────────────────────────────────────────────────────────────── */

void euler_rigid_body_rhs(const double *m, const double *I_diag, double *dm) {
    if (!m || !I_diag || !dm) return;
    double i1 = I_diag[0], i2 = I_diag[1], i3 = I_diag[2];
    dm[0] = m[1] * m[2] * (1.0/i3 - 1.0/i2);
    dm[1] = m[2] * m[0] * (1.0/i1 - 1.0/i3);
    dm[2] = m[0] * m[1] * (1.0/i2 - 1.0/i1);
}

/* ──────────────────────────────────────────────────────────────
 * Euler equations in Lie-Poisson form for so(3)*
 * (More general: dμ/dt = ad*_{∇H} μ)
 *
 * For so(3)*, ad*_ξ μ = μ × ξ (vector cross product).
 * ────────────────────────────────────────────────────────────── */

void so3_lie_poisson_rhs(const double *m, const double *I_diag, double *dm) {
    /* This is identical to euler_rigid_body_rhs for H = ½ Σ m_i²/I_i.
     * For a general Hamiltonian H(m), one computes ∇H and uses:
     *   dm/dt = m × ∇H
     * Here we specialize to the rigid body case. */
    euler_rigid_body_rhs(m, I_diag, dm);
}

/* ──────────────────────────────────────────────────────────────
 * Marsden-Weinstein reduced phase space dimension
 *
 * Marsden-Weinstein-Meyer theorem (1974):
 *   Let (P, ω) be a symplectic manifold with a free and proper
 *   Hamiltonian G-action. Let μ ∈ g* be a regular value of the
 *   momentum map J: P → g*. Then the reduced space
 *     P_μ = J^{-1}(μ) / G_μ
 *   is a symplectic manifold with dimension:
 *     dim(P_μ) = dim(P) - dim(G) - dim(G_μ)
 *
 * where G_μ = {g ∈ G : Ad*_g μ = μ} is the coadjoint isotropy
 * subgroup (stabilizer of μ under the coadjoint action).
 *
 * For a free action, dim(G_μ) = 0, so dim(P_μ) = dim(P) - 2·dim(G).
 * The factor 2 arises because we first restrict to the level set
 * (dim(G) constraints) and then quotient by G_μ (another dim(G_μ)
 * dimensions removed).
 *
 * Example: N particles in R^3 with rotational symmetry.
 *   dim(P) = 6N, G = SO(3) (dim=3), G_μ = SO(2) (dim=1) for μ ≠ 0
 *   dim(P_μ) = 6N - 3 - 1 = 6N - 4
 * ────────────────────────────────────────────────────────────── */

int reduced_phase_space_dimension(int dim_phase, int dim_group, int dim_isotropy) {
    return dim_phase - dim_group - dim_isotropy;
}

/* ──────────────────────────────────────────────────────────────
 * Hamiltonian matrix exponential for quadratic Hamiltonians
 *
 * For H(z) = ½ z^T · S · z where z = [q; p] and S is symmetric,
 * the flow is linear: z(t) = exp(t · J · S) · z(0).
 *
 * The matrix A = J·S is Hamiltonian: A^T J + J A = 0.
 * Its exponential is symplectic: exp(tA)^T J exp(tA) = J.
 *
 * We use a truncated Taylor expansion with scaling-and-squaring
 * for numerical stability.
 * ────────────────────────────────────────────────────────────── */

void hamiltonian_matrix_exponential(const double *S, size_t n, double t,
                                     double *exp_tJS) {
    if (!S || !exp_tJS || n == 0) return;
    size_t n2 = 2 * n;
    size_t n2_sq = n2 * n2;

    /* Compute A = J · S */
    double *J = (double *)malloc(n2_sq * sizeof(double));
    double *A = (double *)malloc(n2_sq * sizeof(double));
    double *A_pow = (double *)malloc(n2_sq * sizeof(double));
    double *result = (double *)malloc(n2_sq * sizeof(double));
    if (!J || !A || !A_pow || !result) {
        free(J); free(A); free(A_pow); free(result); return;
    }

    symplectic_form_matrix(n, J);

    /* A = t * J * S */
    for (size_t i = 0; i < n2; i++) {
        for (size_t j = 0; j < n2; j++) {
            double s = 0.0;
            for (size_t k = 0; k < n2; k++) {
                s += J[i * n2 + k] * S[k * n2 + j];
            }
            A[i * n2 + j] = t * s;
        }
    }

    /* Initialize result = I, A_pow = I */
    memset(result, 0, n2_sq * sizeof(double));
    for (size_t i = 0; i < n2; i++) result[i * n2 + i] = 1.0;
    memcpy(A_pow, result, n2_sq * sizeof(double));

    /* Taylor series: exp(A) = I + A + A^2/2! + A^3/3! + ...
     * Use 12 terms for double precision */
    double factorial = 1.0;
    for (int k = 1; k <= 12; k++) {
        factorial *= (double)k;
        /* A_pow = A_pow * A */
        double *tmp = (double *)malloc(n2_sq * sizeof(double));
        if (!tmp) break;
        memset(tmp, 0, n2_sq * sizeof(double));
        for (size_t i = 0; i < n2; i++) {
            for (size_t j = 0; j < n2; j++) {
                double s = 0.0;
                for (size_t l = 0; l < n2; l++) {
                    s += A_pow[i * n2 + l] * A[l * n2 + j];
                }
                tmp[i * n2 + j] = s;
            }
        }
        memcpy(A_pow, tmp, n2_sq * sizeof(double));
        free(tmp);

        /* result += A_pow / k! */
        for (size_t i = 0; i < n2_sq; i++) {
            result[i] += A_pow[i] / factorial;
        }
    }

    memcpy(exp_tJS, result, n2_sq * sizeof(double));

    free(J); free(A); free(A_pow); free(result);
}

/* ──────────────────────────────────────────────────────────────
 * Random symplectic matrix generator (for testing)
 *
 * Uses the Euler decomposition: M = O · D · O' where O, O' are
 * orthogonal symplectic and D is diagonal symplectic.
 *
 * Simplified: generate via Hamiltonian matrix exponential of a
 * random symmetric matrix S (since exp(J·S) is symplectic).
 * ────────────────────────────────────────────────────────────── */

void random_symplectic_matrix(size_t n, double *M) {
    if (!M || n == 0) return;
    size_t n2 = 2 * n;
    size_t n2_sq = n2 * n2;

    /* Generate random symmetric S */
    double *S = (double *)malloc(n2_sq * sizeof(double));
    if (!S) return;
    for (size_t i = 0; i < n2_sq; i++) S[i] = 0.0;

    /* Simple deterministic "randomness" via a linear congruential generator */
    unsigned int seed = 12345u;
    for (size_t i = 0; i < n2; i++) {
        for (size_t j = i; j < n2; j++) {
            seed = (1103515245u * seed + 12345u) & 0x7fffffffu;
            double val = (double)seed / 0x7fffffffu - 0.5;
            S[i * n2 + j] = val;
            S[j * n2 + i] = val;  /* Symmetric */
        }
    }

    /* M = exp(J·S) with t = 0.5 */
    hamiltonian_matrix_exponential(S, n, 0.5, M);

    free(S);
}
